platform :ios, '7.1'
pod 'AFNetworking', '~> 2.2'
pod 'Foursquare-API-v2', '~> 1.4'
pod 'AKLocationManager', '~> 1.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'Firebase', '~> 1.0.0'
pod 'Facebook-iOS-SDK', '~> 3.13'
